import { Publication, LogEntry } from './types';

export const PUBLICATIONS: Publication[] = [
  {
    id: 'pub1',
    permissions: 'drwxr-xr-x',
    title: 'Digital Radio Mondiale (DRM) transmission and reception in GNU Radio',
    titleEs: 'Digital Radio Mondiale (DRM) transmission and reception in GNU Radio',
    authors: 'Nicolas Javier Salazar Echeverry',
    year:' 2020',
    venue: 'Ungraduate Poster Student on ColCom 2020',
    venueType: 'conference',
    pdfAvailable: false,
    srcAvailable: false,
    bibAvailable: false,
  },
  {
    id: 'pub2',
    permissions: '-rw-r--r--',
    title: 'Radio Signal Identification with Machine Learning and GNU Radio',
    titleEs: 'Identificación de señales radioeléctricas con técnicas de aprendizaje automático y GNU Radio',
    authors: 'Nicolas Javier Salazar Echeverry',
    year: '2022',
    venue: 'Bachelor degree thesis - Icesi University',
    venueType: 'thesis',
    pdfAvailable: false,
    srcAvailable: false,
    bibAvailable: false,
    pdfPath: '',
    doi: '',
  },
  {
    id: 'pub3',
    permissions: '-r--r--r--',
    title: 'Kinect v2 and Orbbec Astra Pro Cameras for Gait Analysis: A Preliminary Comparison',
    titleEs: 'Kinect v2 and Orbbec Astra Pro Cameras for Gait Analysis: A Preliminary Comparison',
    authors: 'A. Navarro, L. Vargas, A. Arteaga, P. Madriñan, N. Salazar, H. Clavijo-Moran',
    year: '2022',
    venue: '2023 IEEE Colombian Caribbean Conference (C3), IEEE',
    venueType: 'conference',
    pdfAvailable: false,
    srcAvailable: false,
    bibAvailable: false,
    doi: 'https://ieeexplore.ieee.org/document/10436293',
  },
  {
    id: 'pub4',
    permissions: 'drwxr-xr-x',
    title: 'Coexistence Study for the 2300-2400MHz IMT band in Colombia',
    titleEs: 'Coexistence Study for the 2300-2400MHz IMT band in Colombia',
    authors: 'A. Navarro, L. Vargas, N. Salazar, A. Serna-Sabater, J. Molina',
    year: '2024',
    venue: 'IEEE Latin America Transactions',
    venueType: 'journal',
    pdfAvailable: false,
    srcAvailable: false,
    bibAvailable: false,
    doi: 'https://ieeexplore.ieee.org/document/10789634',
  },
];

export const SYSTEM_LOG_ENTRIES: LogEntry[] = [ ];
