import { Publication, LogEntry } from './types';

export const PUBLICATIONS: Publication[] = [
  {
    id: 'pub1',
    permissions: 'drwxr-xr-x',
    title: '',
    titleEs: '',
    authors: '',
    year: '2022',
    venue: '',
    venueType: 'premium',
    pdfAvailable: false,
    srcAvailable: false,
    bibAvailable: false,
  },
  {
    id:                 'pub2',
    permissions:  '-rw-r--r--',
    title:                  '',
    titleEs:                '',
    authors:                '',
    year:               '2023',
    venue:                  '',
    venueType:    'conference',
    pdfAvailable:        false,
    srcAvailable:        false,
    bibAvailable:        false,
  },
  {
    id: 'pub3',
    permissions: 'drwxr-xr-x',
    title: '',
    titleEs: '',
    authors: '',
    year: '2023',
    venue: 'Whitepaper',
    venueType: 'whitepaper',
    pdfAvailable: false,
    srcAvailable: false,
    bibAvailable: false,
  },
  {
    id: 'pub4',
    permissions: '-r--r--r--',
    title: '',
    titleEs: '',
    authors: '',
    year: '2022',
    venue: '',
    venueType: 'journal',
    pdfAvailable: false,
    srcAvailable: false,
    bibAvailable: false,
  },
];

export const SYSTEM_LOG_ENTRIES: LogEntry[] = [ ];
