import { Publication, LogEntry } from './types';

export const PUBLICATIONS: Publication[] = [
  {
    id: 'pub1',
    permissions: 'drwxr-xr-x',
    title: 'Onion-Routing-V4: Traffic Analysis Resistance',
    titleEs: 'Onion-Routing-V4: Resistencia al Análisis de Tráfico',
    authors: 'Alice Smith, Bob Johnson, Charlie Davis',
    year: '2024',
    venue: 'USENIX Security',
    venueType: 'premium',
    pdfAvailable: true,
    srcAvailable: true,
    bibAvailable: true,
  },
  {
    id: 'pub2',
    permissions: '-rw-r--r--',
    title: 'Zero-Knowledge Proofs for Anonymous Messaging',
    titleEs: 'Pruebas de Conocimiento Cero para Mensajería Anónima',
    authors: 'D. Wilson, E. Brown',
    year: '2023',
    venue: 'BlackHat USA',
    venueType: 'conference',
    pdfAvailable: true,
    srcAvailable: false,
    bibAvailable: true,
  },
  {
    id: 'pub3',
    permissions: 'drwxr-xr-x',
    title: 'Quantum Resistance in Decentralized Identifiers',
    titleEs: 'Resistencia Cuántica en Identificadores Descentralizados',
    authors: 'Research Consortium',
    year: '2023',
    venue: 'Whitepaper',
    venueType: 'whitepaper',
    pdfAvailable: true,
    srcAvailable: true,
    bibAvailable: false,
  },
  {
    id: 'pub4',
    permissions: '-r--r--r--',
    title: 'Latency Optimization in Multi-Hop Networks',
    titleEs: 'Optimización de Latencia en Redes Multi-salto',
    authors: 'F. Taylor, G. White',
    year: '2022',
    venue: 'IEEE S&P',
    venueType: 'journal',
    pdfAvailable: true,
    srcAvailable: false,
    bibAvailable: true,
  },
];

export const SYSTEM_LOG_ENTRIES: LogEntry[] = [
  {
    id: 'log1',
    tag: 'SECURITY',
    date: '2023-10-24 14:32',
    readTime: '8 MIN READ',
    readTimeEs: '8 MIN DE LECTURA',
    command: 'cat reverse_engineering_firmware.md',
    description: 'An in-depth analysis of proprietary IoT protocols and the vulnerabilities hidden within obfuscated binary blobs. We explore how to extract entropy from limited hardware sources...',
    descriptionEs: 'Un análisis en profundidad de los protocolos IoT propietarios y las vulnerabilidades ocultas dentro de blobs binarios ofuscados. Exploramos cómo extraer entropía de fuentes de hardware limitadas...',
    blogPostId: 'reverse-engineering-firmware',
  },
  {
    id: 'log2',
    tag: 'TOR_NETWORK',
    date: '2023-09-12 09:15',
    readTime: '12 MIN READ',
    readTimeEs: '12 MIN DE LECTURA',
    command: 'cat the_onion_router_evolution.md',
    description: 'Tracing the architectural shifts from early circuit building to current v3 onion services. Why modern censorship resistance requires more than just multi-hop encryption.',
    descriptionEs: 'Rastreando los cambios arquitectónicos desde la construcción de circuitos tempranos hasta los actuales servicios onion v3. Por qué la resistencia a la censura moderna requiere más que solo cifrado multi-salto.',
    blogPostId: 'the-tor-network-outlook',
  },
  {
    id: 'log3',
    tag: 'PRIVACY',
    date: '2023-08-30 22:48',
    readTime: '5 MIN READ',
    readTimeEs: '5 MIN DE LECTURA',
    command: 'cat metadata_sanitization_guide.md',
    description: 'Your files are shouting your identity. A technical breakdown of EXIF, XMP, and system-level forensic artifacts that leak your location and device signature.',
    descriptionEs: 'Tus archivos están gritando tu identidad. Un desglose técnico de EXIF, XMP y artefactos forenses a nivel de sistema que filtran tu ubicación y firma de dispositivo.',
    blogPostId: 'escaping-the-metadata-trap',
  },
  {
    id: 'log4',
    tag: 'CRYPTOGRAPHY',
    date: '2023-10-24 08:12',
    readTime: '12 MIN READ',
    readTimeEs: '12 MIN DE LECTURA',
    command: 'cat zero_knowledge_identities.md',
    description: 'Detailed analysis of zero-knowledge proofs applied within decentralized identifier consensus layers, explaining mathematical checks.',
    descriptionEs: 'Análisis detallado de pruebas de conocimiento cero aplicadas dentro de capas de consenso de identificadores descentralizados, explicando comprobaciones matemáticas.',
    blogPostId: 'zero-knowledge-foundations',
  },
];
